
# Exception Effect
Exception effect allows you to create a throw operation to break out of the flow of your program.

---


## Import it in your project
```js
import { Exception } from '@algebraic-effects/effects';
```


## API

### Functions

* `Exception.try`
It accepts a program (generator with effects) and returns a task
```haskell
try :: (Program<Exception> ...a b, ...a) -> Task e b
```


### Operations
```js
Exception = {
  throw: func(['error']),
}
```


## Usage examples

### Using Exception effect
You can use the Exception effect to handle error flows in your application. This gives you more control of the flow of the program than the traditional throw with `try/catch`.

```js
import { Exception } from '@algebraic-effects/core';

const divide = function *(a, b) {
  if (b === 0) yield Exception.throw(new Error('Invalid operation'));
  yield a / b;
};

Exception.try(divide, 5, 2)
  .fork(() => {}, result => console.log('5 / 2 ===', result));

Exception.try(divide, 5, 0)
  .fork(e => console.error(e), () => {});
```



### Custom handler for Exception effect (toEither)

```js
import { Exception } from '@algebraic-effects/core';
import Either from 'crocks/Either'; // Using Either from crocks

// divide :: Program<Exception> (Number, Number) Number
const divide = function *(a, b) {
  if (b === 0) yield Exception.throw(new Error('Invalid operation'));
  yield a / b;
};

// toEither :: (Program<Exception> (...a)  b, ...a) -> Task.Resolved (Either Error b)
const toEither = Exception.handler({
  throw: ({ end }) => error => end(Either.Left(error.message)),
  _: ({ end }) => value => end(Either.Right(value)),
});

await toEither(divide, 5, 2).toPromise(); // Either.Right 2.5
await toEither(divide, 5, 0).toPromise(); // Either.Left 'Invalid operation'
```
